const ProjectData = [
  {
    title:
      "Leveraging Machine Learning for Proactive Detection and Mitigation of Android RAT",
    description:
      "AI-powered detection of Android RATs: proactively securing mobile environments with advanced machine learning.",
    image: "src/assets/images/UROP.png",
    endpoint: "/Project1",
    projectLink: "https://github.com/JithinPonduru/Android-RAT-Detection",
    detailedDescription:
      "With the increasing threats of Android Remote Access Trojans (RATs), this project aims to build an intelligent system capable of identifying and mitigating RATs in real time. By leveraging ensemble learning algorithms like Random Forest and Gradient Boosting, we achieve high detection accuracy, ensuring that suspicious activities can be flagged and mitigated quickly to prevent security breaches. Key Technologies: Python for building machine learning models and performing data analysis, Ensemble Learning with models such as Random Forest and Gradient Boosting to boost detection accuracy, Network Traffic Analysis with custom feature extraction techniques for accurate RAT detection, Data Preprocessing techniques like normalization, scaling, and data augmentation to handle varied traffic data. Challenges Overcome: Handling complex, diverse network traffic generated by multiple RAT types, Minimizing false positives while maintaining real-time detection capabilities, Balancing accuracy with computational efficiency for high-speed traffic analysis. Impact: This system enhances Android device security by providing proactive detection and mitigation of RATs, protecting sensitive data from exploitation and reducing cybersecurity risks. Potential Applications: Mobile security apps for enterprise environments, Network monitoring tools for cybersecurity firms, Device management platforms with built-in RAT protection.",
    usedTechnologies: [
      "Python",
      "TensorFlow",
      "Random Forest",
      "Gradient Boosting",
      "Network Traffic Analysis",
    ],
    TimeLine: [
      {
        Period: "Aug 2023",
        Date: 1,
        Description: "Started working on the project",
      },
      {
        Period: "Sep 2023",
        Date: 1,
        Description: "Collected data and performed data preprocessing",
      },
      {
        Period: "Oct 2023",
        Date: 1,
        Description: "Built machine learning models and conducted experiments",
      },
      {
        Period: "Nov 2023",
        Date: 1,
        Description: "Analyzed results and fine-tuned the models",
      },
      {
        Period: "Dec 2023",
        Date: 1,
        Description: "Completed the project and submitted the final report",
      },
      {
        Period: "Jan 2024",
        Date: 1,
        Description: "Applied for ACSS 2024 conference",
      },
      {
        Period: "Feb 2024",
        Date: 1,
        Description: "Received acceptance for the conference",
      },
      {
        Period: "Jul 2024",
        Date: 1,
        Description: "Presented the paper at ACSS 2024 conference",
      },
    ],
    PaperLink: "https://link.springer.com/article/10.1007/s11334-024-00572-3",
  },
  {
    title: "Tender System and Security using Blockchain",
    description:
      "TenderChain: a blockchain-based system ensuring secure, transparent, and efficient tender management.",
    image: "src/assets/images/Tender1.jpg",
    endpoint: "/Project2",
    projectLink: "https://github.com/JithinPonduru/TenderChain",
    detailedDescription:
      "This project uses blockchain to automate and secure the management of tender processes, ensuring transparency, immutability, and tamper-proof contract management. Smart contracts facilitate decentralized transactions, reducing the chances of fraud and ensuring trust between all parties involved. Key Technologies: Solidity for writing smart contracts on the Ethereum blockchain, Blockchain to ensure transparent and secure contract management, IPFS for decentralized file storage and document sharing, Web3.js to integrate blockchain functionalities with a web interface for ease of use. Challenges Overcome: Ensuring secure handling of sensitive contract data, Overcoming integration complexities with existing tender systems, Addressing scalability issues in decentralized systems managing large contracts. Impact: This project transforms tender management by providing a secure, transparent, and immutable system. It minimizes fraud and data tampering, fostering a fairer bidding process and ensuring better regulatory compliance across industries. Potential Applications: Government contract management systems, Corporate procurement platforms with secure bidding processes, Global tender management systems in sectors like construction, IT, and healthcare.",
    usedTechnologies: ["Solidity", "Ethereum Blockchain", "IPFS", "Web3.js"],
    TimeLine: [
      {
        Period: "Jan 2024",
        Date: 1,
        Description: "Started working on the project",
      },
      {
        Period: "Jan 2024",
        Date: 2,
        Description: "UI/UX Design and Frontend Development",
      },
      {
        Period: "Jan 2024",
        Date: 3,
        Description:
          "Overview of the project and its requirements including the Smart Contract Requirements",
      },
      {
        Period: "Feb 2024",
        Date: 1,
        Description:
          "Developed the Smart Contracts and integrated them with the Frontend",
      },
      {
        Period: "Feb 2024",
        Date: 2,
        Description: "Integration of all the components and testing",
      },
      { Period: "Mar 2024", Date: 1, Description: "Testing and Debugging" },
      {
        Period: "Mar 2024",
        Date: 2,
        Description: "Deployment and User Testing",
      },
      { Period: "Mar 2024", Date: 3, Description: "Final Report Submission" },
      {
        Period: "Aug 2024",
        Date: 1,
        Description: "Started working on the Project Paper presentation",
      },
      {
        Period: "Nov 2024",
        Date: 1,
        Description: "Done with the Paper Writing",
      },
    ],
    PaperLink:"https://tender-chain.vercel.app/"
  },
  {
    title: "Smart Student Outpass System",
    description:
      "Smart Student OutPass System automates and secures student outpass requests with IoT integration and real-time monitoring.",
    image: "src/assets/images/SSOS.jpg",
    endpoint: "/Project3",
    projectLink: "https://github.com/JithinPonduru/Student-Outpass-System",
    detailedDescription:
      "This IoT-enabled system streamlines the student outpass process, integrating real-time location tracking with automated approvals. It reduces administrative overhead while ensuring student safety and accountability through automated notifications and easy access to data. Key Technologies: Django for backend management, including student data handling and notifications, IoT integration with ESP32 for location tracking, MicroPython for programming the ESP32 to monitor and report student locations, React for frontend development, providing an intuitive interface for students and admins. Challenges Overcome: Ensuring reliable, accurate tracking of student locations through IoT, Securing student data and ensuring privacy, Developing a consistent user experience across multiple platforms (web and mobile). Impact: The Smart Student Outpass System enhances campus administration by automating and simplifying the outpass process, ensuring a safe, efficient, and user-friendly experience for both students and administrators. Potential Applications: University and college campuses, Smart campus systems incorporating IoT, Security and monitoring solutions for educational institutions.",
    usedTechnologies: ["Django", "ESP32", "MicroPython", "React"],
    TimeLine: [
      {
        Period: "Jan 2024",
        Date: 1,
        Description: "Started working on the project",
      },
      {
        Period: "Jan 2024",
        Date: 2,
        Description:
          "UI/UX Design and gathering the requirements including the IoT requirements",
      },
      {
        Period: "Feb 2024",
        Date: 1,
        Description: "Developed the Backend and integrated the IoT devices",
      },
      {
        Period: "Feb 2024",
        Date: 2,
        Description: "Testing and Debugging the developed Backend",
      },
      {
        Period: "Feb 2024",
        Date: 3,
        Description:
          "Developed the Frontend and integrated it with the Backend",
      },
      {
        Period: "Mar 2024",
        Date: 1,
        Description: "Testing and Debugging the Frontend",
      },
      {
        Period: "Mar 2024",
        Date: 2,
        Description: "Deployment and User Testing",
      },
      { Period: "Mar 2024", Date: 3, Description: "Final Report Submission" },
      {
        Period: "Aug 2024",
        Date: 1,
        Description: "Applied for the Patent on the Project",
      },
    ],
  },
  {
    title: "Bingo-25",
    description:
      "Bingo-25: An innovative solution for enhancing user engagement and interactive gameplay with real-time features.",
    image: "src/assets/images/Bingo.png",
    endpoint: "/Project4",
    projectLink: "https://github.com/JithinPonduru/Bingo_BackEnd",
    detailedDescription:
      "Bingo-25 offers a modernized, interactive version of the classic Bingo game. With both single-player and multiplayer modes, it engages players in competitive and fun gameplay. The unique 5x5 grid layout adds an interesting twist to the traditional format. Key Technologies: React for creating the interactive frontend, Node.js for managing the backend and multiplayer functionality, WebSocket for real-time communication between players, HTML5 Canvas for displaying dynamic Bingo grids. Challenges Overcome: Ensuring smooth multiplayer gameplay with real-time synchronization, Designing an appealing interface that attracts both traditional Bingo players and new users, Handling edge cases in the game logic, including correct card generation and number calling. Impact: Bingo-25 modernizes the classic Bingo experience, providing entertainment for players of all ages. It is ideal for online gaming platforms, mobile apps, and social media integrations. Potential Applications: Online gaming platforms, Mobile apps for casual gaming, Social media integrations for user engagement.",
    usedTechnologies: ["React", "Node.js", "WebSocket", "HTML5 Canvas"],
    TimeLine: [
      {
        Date: { Period: "Aug 2024", Day: 1 },
        Description: "Started working on the project",
      },
      {
        Date: { Month: "Aug 2024", Day: 2 },
        Description: "Frontend requirements and design analysis",
      },
      {
        Date: { Month: "Aug 2024", Day: 3 },
        Description: "Backend development and API integration (Socket.io)",
      },
      {
        Date: { Month: "Sep 2024", Day: 4 },
        Description: "Frontend and Backend integration",
      },
      {
        Date: { Month: "Sep 2024", Day: 5 },
        Description: "Testing and Debugging",
      },
      {
        Date: { Month: "Sep 2024", Day: 6 },
        Description: "Deployment and User Testing",
      },
      {
        Date: { Month: "Sep 2024", Day: 7 },
        Description: "Project Put to Live",
      },
    ],
    PaperLink:"https://bingo-25.netlify.app/"
  },
];

export default ProjectData;
